// 2-SymmetryEnforcement.fs
// Enforcement and verification of physical symmetries for hexagonal lattice PEPS tensors.
namespace E8.TensorConstruction

open System.Collections.Generic
open E8.Algebra
open E8.Tensors

/// Module for enforcing and verifying symmetries in PEPS tensors.
module SymmetryEnforcement =

    /// Types of symmetry operations relevant to a hexagonal lattice PEPS tensor.
    /// A hexagonal PEPS tensor has 3 virtual legs. The most fundamental symmetries
    /// are the cyclic permutations (rotations) and reflections of these legs.
    type SymmetryOperation =
        | Identity         // No change: (v1, v2, v3) -> (v1, v2, v3)
        | Rotation120      // 120-degree rotation (C3): (v1, v2, v3) -> (v2, v3, v1)
        | Rotation240      // 240-degree rotation (C3^2): (v1, v2, v3) -> (v3, v1, v2)
        | Reflection1      // Reflection across axis bisecting v1: (v1, v2, v3) -> (v1, v3, v2)
        | Reflection2      // Reflection across axis bisecting v2: (v1, v2, v3) -> (v3, v2, v1)
        | Reflection3      // Reflection across axis bisecting v3: (v1, v2, v3) -> (v2, v1, v3)

    /// Applies a symmetry operation to the 3 virtual tensor indices.
    let applySymmetryToIndices (op: SymmetryOperation) (v1: int, v2: int, v3: int) : (int * int * int) =
        match op with
        | Identity -> (v1, v2, v3)
        | Rotation120 -> (v2, v3, v1)
        | Rotation240 -> (v3, v1, v2)
        | Reflection1 -> (v1, v3, v2)
        | Reflection2 -> (v3, v2, v1)
        | Reflection3 -> (v2, v1, v3)

    /// Applies a symmetry operation to a tensor element by transforming its indices.
    let applySymmetryToTensor (tensor: Tensor4F2) (op: SymmetryOperation) (p: int) (v1: int) (v2: int) (v3: int) : F2 =
        let (v1', v2', v3') = applySymmetryToIndices op (v1, v2, v3)
        tensor.[p, v1', v2', v3']

    /// Checks if a tensor respects a given symmetry.
    /// Returns a tuple: (isSymmetric: bool, violationCount: int)
    let checkSymmetry (tensor: Tensor4F2) (op: SymmetryOperation) : bool * int =
        let physDim = tensor.D1
        let bondDim = tensor.D2 // Assumes D2=D3=D4
        let mutable violations = 0
        let mutable isSymmetric = true

        for p in 0 .. physDim - 1 do
            for v1 in 0 .. bondDim - 1 do
                for v2 in 0 .. bondDim - 1 do
                    for v3 in 0 .. bondDim - 1 do
                        let original = tensor.[p, v1, v2, v3]
                        let transformed = applySymmetryToTensor tensor op p v1 v2 v3

                        if original <> transformed then
                            isSymmetric <- false
                            violations <- violations + 1
        (isSymmetric, violations)

    /// Enforces a specific symmetry on the tensor by averaging element values.
    let enforceSymmetry (tensor: Tensor4F2) (op: SymmetryOperation) : unit =
        let physDim = tensor.D1
        let bondDim = tensor.D2

        // A set to track elements that have already been part of a symmetrization group.
        let processed = HashSet<int * int * int * int>()

        for p in 0 .. physDim - 1 do
            for v1 in 0 .. bondDim - 1 do
                for v2 in 0 .. bondDim - 1 do
                    for v3 in 0 .. bondDim - 1 do
                        let key = (p, v1, v2, v3)

                        if not (processed.Contains(key)) then
                            // Get the transformed indices and key
                            let (v1', v2', v3') = applySymmetryToIndices op (v1, v2, v3)
                            let transformedKey = (p, v1', v2', v3')

                            // Get both values
                            let original = tensor.[p, v1, v2, v3]
                            let transformed = tensor.[p, v1', v2', v3']

                            // Symmetrize by taking the OR (logical sum in F2 context)
                            // This ensures that if any path is allowed, the symmetrized path is allowed.
                            let symmetrized = if original = F2.One || transformed = F2.One then F2.One else F2.Zero

                            // Set both elements to the symmetrized value
                            tensor.[p, v1, v2, v3] <- symmetrized
                            tensor.[p, v1', v2', v3'] <- symmetrized

                            // Mark both as processed to avoid redundant work
                            processed.Add(key) |> ignore
                            processed.Add(transformedKey) |> ignore

    /// Enforces the full C3 rotational symmetry group on the tensor.
    /// This is the most crucial symmetry for the hexagonal lattice.
    let enforceC3Symmetry (tensor: Tensor4F2) : unit =
        // The C3 group is generated by the 120-degree rotation.
        // We enforce this by averaging over the orbit of each index tuple.
        let physDim = tensor.D1
        let bondDim = tensor.D2
        let processed = HashSet<int * int * int * int>()

        for p in 0 .. physDim - 1 do
            for v1 in 0 .. bondDim - 1 do
                for v2 in 0 .. bondDim - 1 do
                    for v3 in 0 .. bondDim - 1 do
                        let key1 = (p, v1, v2, v3)
                        if not (processed.Contains(key1)) then
                            // Get the orbit under C3 rotation
                            let (v1_r1, v2_r1, v3_r1) = applySymmetryToIndices Rotation120 (v1, v2, v3)
                            let key2 = (p, v1_r1, v2_r1, v3_r1)

                            let (v1_r2, v2_r2, v3_r2) = applySymmetryToIndices Rotation240 (v1, v2, v3)
                            let key3 = (p, v1_r2, v2_r2, v3_r2)

                            // Get the values for the three elements in the orbit
                            let val1 = tensor.[p, v1, v2, v3]
                            let val2 = tensor.[p, v1_r1, v2_r1, v3_r1]
                            let val3 = tensor.[p, v1_r2, v2_r2, v3_r2]

                            // Symmetrize by taking the logical OR (if any is 1, all become 1)
                            let symmetrized = if val1 = F2.One || val2 = F2.One || val3 = F2.One then F2.One else F2.Zero

                            // Apply the symmetrized value to all elements in the orbit
                            tensor.[p, v1, v2, v3] <- symmetrized
                            tensor.[p, v1_r1, v2_r1, v3_r1] <- symmetrized
                            tensor.[p, v1_r2, v2_r2, v3_r2] <- symmetrized

                            // Mark all elements in the orbit as processed
                            processed.Add(key1) |> ignore
                            processed.Add(key2) |> ignore
                            processed.Add(key3) |> ignore

    /// Verifies all defined symmetries for the hexagonal tensor and returns a report.
    let verifyAllSymmetries (tensor: Tensor4F2) : bool =
        let allSymmetries = [
            (Identity, "Identity")
            (Rotation120, "120-degree rotation (C3)")
            (Rotation240, "240-degree rotation (C3^2)")
            (Reflection1, "Reflection across axis 1")
            (Reflection2, "Reflection across axis 2")
            (Reflection3, "Reflection across axis 3")
        ]

        let mutable allSymmetric = true

        for (sym, name) in allSymmetries do
            if sym <> Identity then
                let (isSymmetric, violations) = checkSymmetry tensor sym
                if not isSymmetric then
                    // In a test context, this would fail. Here we just track it.
                    allSymmetric <- false

        allSymmetric

    /// Computes the symmetry defect (how far from symmetric) as a measure of error.
    let computeSymmetryDefect (tensor: Tensor4F2) : float =
        let symmetriesToTest = [
            Rotation120; Rotation240; Reflection1; Reflection2; Reflection3
        ]

        let mutable totalViolations = 0

        for sym in symmetriesToTest do
            let (_, violations) = checkSymmetry tensor sym
            totalViolations <- totalViolations + violations

        let totalElementsChecked = tensor.TotalElements * symmetriesToTest.Length
        if totalElementsChecked = 0 then 0.0 else float totalViolations / float totalElementsChecked